[tool.pyright]
include = ["*"]

# ignore = ["src/oldstuff"]
# defineConstant = { DEBUG = true }
# stubPath = "src/stubs"

# reportMissingImports = true
# reportMissingTypeStubs = false

# pythonVersion = "3.6"
# pythonPlatform = "Linux"

executionEnvironments = [{ root = "*" }]
